name: Build Project

on:
  push:
    branches: [master, ver/*]
  pull_request:
    branches: [master, ver/*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun ci
      - name: Build Package
        run: bun run build
      - name: Run Tests
        run: bun run test:coverage
      - name: Code Coverage Summary Report
        uses: saschanowak/CloverCodeCoverageSummary@1.1.1
        with:
          filename: coverage/clover.xml
      - name: Code Coverage Report (Workflow Summary)
        run: |
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY
          cat code-coverage-details.md >> $GITHUB_STEP_SUMMARY
      - name: Code Coverage Report (Pull Request)
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-summary.md

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun ci
      - name: Generate JSDoc
        run: |
          bun run compile
          bun run doc
      - name: Deploy
        run: bash jsdoc.sh ${GITHUB_SHA::7}
