name: Build & Test

on:
  push:
    branches: [master, ver/*]
  pull_request:
    branches: [master, ver/*]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun ci
      - name: Build Package
        run: bun run build
      - name: Run Tests
        run: bun run test:coverage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy JSDoc
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun ci
      - name: Generate JSDoc
        run: |
          bun run compile
          bun run doc
      - name: Deploy
        run: bash jsdoc.sh ${GITHUB_SHA::7}
